/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as PaymentsRouteImport } from './routes/payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ai': typeof AiRoute
  '/automation': typeof AutomationRoute
  '/cloud': typeof CloudRoute
  '/infrastructure': typeof InfrastructureRoute
  '/messaging': typeof MessagingRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ai': typeof AiRoute
  '/automation': typeof AutomationRoute
  '/cloud': typeof CloudRoute
  '/infrastructure': typeof InfrastructureRoute
  '/messaging': typeof MessagingRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/ai': typeof AiRoute
  '/automation': typeof AutomationRoute
  '/cloud': typeof CloudRoute
  '/infrastructure': typeof InfrastructureRoute
  '/messaging': typeof MessagingRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/ai'
    | '/automation'
    | '/cloud'
    | '/infrastructure'
    | '/messaging'
    | '/payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/ai'
    | '/automation'
    | '/cloud'
    | '/infrastructure'
    | '/messaging'
    | '/payments'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/ai'
    | '/automation'
    | '/cloud'
    | '/infrastructure'
    | '/messaging'
    | '/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AiRoute: typeof AiRoute
  AutomationRoute: typeof AutomationRoute
  CloudRoute: typeof CloudRoute
  InfrastructureRoute: typeof InfrastructureRoute
  MessagingRoute: typeof MessagingRoute
  PaymentsRoute: typeof PaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AiRoute: AiRoute,
  AutomationRoute: AutomationRoute,
  CloudRoute: CloudRoute,
  InfrastructureRoute: InfrastructureRoute,
  MessagingRoute: MessagingRoute,
  PaymentsRoute: PaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
